### ISSUE TITLE
My Impression of this library.

### ISSUE THREAD

**Issue by chunhtai** [gskinnerTeam/flutter_nav_stack#1]
I think this is an interesting approach. Just would like to leave some feedback.

Navigator is a giant wrapper over Overlay which is a giant wrapper over Stack. I think you have reimplemented a bunch of things in here. This looks fine, but I wonder how you would support the hero animation since it is currently tightly bounded with the navigator route transition. Although this may not be a problem if we refactored hero controller.
Ref ttps://github.com/flutter/flutter/issues/54200

**Comment by esDotDev** [comment]
Thanks for the feedback! 

Currently there is no way to support Hero with this approach, as this is basically a single route, that uses an `IndexedStack` under the hood.  

So this does re-implement basic route switching, and yes we lose Hero, but on the plus side, we maintain state in all routes and can add persistent scaffolds / nesting easily.

It would be great if Hero's could be improved to not rely on page route transitions, this would fix one of the the bigger downsides to this approach.
